<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Post Schedule - {{ $dayName }} - PALLADIUM MALL</title>
    <!-- Tailwind CSS CDN -->
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @media print {
            @page {
                size: A4 portrait;
                margin: 0.5cm;
            }
            .no-print {
                display: none !important;
            }
            body {
                background-color: white !important;
                color: black !important;
                padding: 0 !important;
                margin: 0 !important;
                zoom: 0.88;
            }
            .print-container {
                max-width: 100% !important;
                padding: 0 !important;
                margin: 0 !important;
                border: none !important;
                box-shadow: none !important;
            }
            .page-break {
                page-break-after: always;
            }
        }
    </style>
</head>
<body class="bg-gray-100 text-gray-900 antialiased min-h-screen p-4 sm:p-8 font-sans">

    <!-- ACTION BUTTONS (HIDDEN DURING PRINT) -->
    <div class="max-w-5xl w-full mx-auto mb-6 flex items-center justify-between gap-3 no-print">
        <div class="flex items-center gap-2">
            <a href="{{ route('post-schedules.index', ['day' => $selectedDay]) }}"
                class="inline-flex items-center gap-1.5 rounded-xl border border-gray-300 bg-white px-4 py-2 text-xs font-bold text-gray-700 hover:bg-gray-50 shadow-xs transition-all">
                ← Back to Schedule
            </a>
            <span class="text-xs text-gray-500 font-semibold">
                Showing {{ $dayName }} duties ({{ $totalEntries }} items)
            </span>
        </div>

        <div class="flex items-center gap-2">
            <button onclick="window.print()"
                class="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-bold text-white shadow-md hover:bg-blue-700 transition-all cursor-pointer">
                🖨️ Print Daily Roster
            </button>
            <button onclick="window.close()"
                class="inline-flex items-center gap-2 rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm font-semibold text-gray-700 hover:bg-gray-50 transition-all shadow-xs cursor-pointer">
                Close
            </button>
        </div>
    </div>

    <!-- PRINTABLE ROSTER CONTAINER -->
    <div class="max-w-5xl w-full mx-auto print-container rounded-3xl bg-white p-6 sm:p-10 border border-gray-300 shadow-xl text-gray-900">

        <!-- HEADER: CENTERED TITLE WITH BRANDING -->
        <div class="text-center mb-6 pb-4 border-b-2 border-gray-800">
            <h1 class="text-2xl sm:text-3xl font-black tracking-wider text-gray-900 uppercase mb-0.5">
                PALLADIUM MALL
            </h1>
            <p class="text-xs font-bold text-gray-600 uppercase tracking-widest mb-1.5">
                Management Office & Operations
            </p>
            <h2 class="text-xl sm:text-2xl font-black tracking-tight text-blue-700 uppercase">
                Daily Post Schedule & Duty Roster
            </h2>
        </div>

        <!-- METADATA & SUMMARY BANNER -->
        <div class="grid grid-cols-2 sm:grid-cols-4 gap-4 p-4 rounded-2xl bg-gray-50 border border-gray-300 text-xs mb-6">
            <div>
                <span class="text-gray-500 block text-[10px] font-bold uppercase tracking-wider">Schedule Day:</span>
                <span class="font-black text-sm text-blue-700 uppercase">{{ $dayName }}</span>
            </div>
            <div>
                <span class="text-gray-500 block text-[10px] font-bold uppercase tracking-wider">Date / Period:</span>
                <span class="font-bold text-gray-900">{{ $reportDate }}</span>
            </div>
            <div>
                <span class="text-gray-500 block text-[10px] font-bold uppercase tracking-wider">Total Post Duties:</span>
                <span class="font-bold text-gray-900">{{ $totalEntries }} Active Posts</span>
            </div>
            <div>
                <span class="text-gray-500 block text-[10px] font-bold uppercase tracking-wider">Generated By:</span>
                <span class="font-bold text-gray-900">{{ auth()->user()->name ?? 'Super Admin' }}</span>
            </div>
        </div>

        <!-- POST SCHEDULE DUTIES GROUPED BY POST HEAD -->
        @if($groupedSchedules->isEmpty())
            <div class="p-8 text-center border border-dashed border-gray-300 rounded-2xl text-gray-400 font-semibold">
                No active post duties scheduled for {{ $dayName }}.
            </div>
        @else
            @foreach($groupedSchedules as $headId => $items)
                @php
                    $head = $heads[$headId] ?? null;
                @endphp
                <div class="mb-6">
                    {{-- Section Head Banner --}}
                    <div class="flex items-center justify-between px-3 py-1.5 rounded-lg bg-gray-800 text-white text-xs font-black uppercase tracking-wide mb-2">
                        <span>🏷️ {{ $head ? $head->name : 'General Duties' }}</span>
                        <span class="text-[11px] font-normal text-gray-300">{{ $items->count() }} assigned staff</span>
                    </div>

                    {{-- Table --}}
                    <table class="w-full text-left text-xs border-collapse border border-gray-300">
                        <thead>
                            <tr class="bg-gray-100 text-gray-800 uppercase text-[10px] tracking-wider font-extrabold">
                                <th class="border border-gray-300 px-2.5 py-2 text-center w-8">#</th>
                                <th class="border border-gray-300 px-3 py-2 w-36">Location / Post</th>
                                <th class="border border-gray-300 px-3 py-2 w-28">Shift / Timing</th>
                                <th class="border border-gray-300 px-3 py-2 w-36">Assigned Staff</th>
                                <th class="border border-gray-300 px-3 py-2">Task & Duty Instructions</th>
                                <th class="border border-gray-300 px-3 py-2 w-28 text-center">Staff Sign</th>
                                <th class="border border-gray-300 px-3 py-2 w-28 text-center">Supervisor</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-gray-200 font-medium">
                            @foreach($items as $i => $item)
                                <tr class="{{ $loop->even ? 'bg-gray-50/50' : 'bg-white' }}">
                                    <td class="border border-gray-300 px-2.5 py-2.5 text-center font-bold text-gray-500">
                                        {{ $i + 1 }}
                                    </td>
                                    <td class="border border-gray-300 px-3 py-2.5 font-bold text-gray-900">
                                        {{ $item->location ?: '—' }}
                                    </td>
                                    <td class="border border-gray-300 px-3 py-2.5 font-mono font-bold text-gray-800">
                                        {{ $item->shift_display }}
                                    </td>
                                    <td class="border border-gray-300 px-3 py-2.5">
                                        <div class="font-black text-gray-900">{{ $item->employee_name }}</div>
                                        @if($item->user)
                                            <div class="text-[10px] text-gray-500 font-normal">({{ $item->user->name }})</div>
                                        @endif
                                    </td>
                                    <td class="border border-gray-300 px-3 py-2.5">
                                        <div class="font-bold text-gray-900 mb-0.5">{{ $item->task_title }}</div>
                                        @if($item->duties)
                                            <div class="text-[11px] text-gray-600 whitespace-pre-line leading-relaxed">{{ $item->duties }}</div>
                                        @endif
                                        @if($item->notes)
                                            <div class="text-[10px] text-amber-700 italic mt-0.5">Note: {{ $item->notes }}</div>
                                        @endif
                                    </td>
                                    <td class="border border-gray-300 px-2 py-2.5 text-center align-bottom">
                                        <div class="border-b border-dashed border-gray-400 h-6"></div>
                                    </td>
                                    <td class="border border-gray-300 px-2 py-2.5 text-center align-bottom">
                                        <div class="border-b border-dashed border-gray-400 h-6"></div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            @endforeach
        @endif

        <!-- SIGNATURE AND VERIFICATION FOOTER -->
        <div class="grid grid-cols-3 gap-6 pt-12 mt-8 border-t border-gray-300 text-center text-xs">
            <div>
                <div class="border-b border-gray-500 w-40 mx-auto mb-1"></div>
                <p class="font-bold text-gray-800">Prepared By</p>
                <p class="text-[10px] text-gray-500">Duty Coordinator</p>
            </div>
            <div>
                <div class="border-b border-gray-500 w-40 mx-auto mb-1"></div>
                <p class="font-bold text-gray-800">Verified By</p>
                <p class="text-[10px] text-gray-500">Operations Supervisor</p>
            </div>
            <div>
                <div class="border-b border-gray-500 w-40 mx-auto mb-1"></div>
                <p class="font-bold text-gray-800">Authorized Signature</p>
                <p class="text-[10px] text-gray-500">Mall Management</p>
            </div>
        </div>

        <div class="mt-6 text-center text-[10px] text-gray-400 border-t border-gray-100 pt-2">
            Palladium Mall Operations System • Printed on {{ now()->format('d M Y, h:i A') }}
        </div>
    </div>

</body>
</html>
